from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
UI_DIR = ROOT / "app" / "ui"
OUTPUT_PATH = ROOT / "app" / "ui_assets.py"
ASSET_FILES = [
    ("INDEX_HTML", "index.html"),
    ("STYLES_CSS", "styles.css"),
    ("APP_JS", "app.js"),
]


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _render_module() -> str:
    lines = [
        "# Auto-generated by scripts/embed_ui_assets.py",
        "# Do not edit this file directly; edit files under app/ui/ instead.",
        "",
    ]
    mapping_entries: list[str] = []
    for constant_name, filename in ASSET_FILES:
        content = _read_text(UI_DIR / filename)
        lines.append(f"{constant_name} = {json.dumps(content, ensure_ascii=False)}")
        lines.append("")
        mapping_entries.append(f'    "{filename}": {constant_name},')
    lines.append("UI_ASSETS = {")
    lines.extend(mapping_entries)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    OUTPUT_PATH.write_text(_render_module(), encoding="utf-8")
    print(f"Updated {OUTPUT_PATH.relative_to(ROOT)} from app/ui assets.")


if __name__ == "__main__":
    main()
